// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmy8TgeNVnPPeHUVAouB6jIZo5EJ4MHho',
    appId: '1:471990946641:web:e22ecb2b1a3e4ae9672170',
    messagingSenderId: '471990946641',
    projectId: 'web-wrapper-app',
    authDomain: 'web-wrapper-app.firebaseapp.com',
    storageBucket: 'web-wrapper-app.firebasestorage.app',
    measurementId: 'G-WHDGZLCQTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwo1BkkQfPS4qs0DutkOahPCMgOnum194',
    appId: '1:471990946641:android:af9f4145125831a2672170',
    messagingSenderId: '471990946641',
    projectId: 'web-wrapper-app',
    storageBucket: 'web-wrapper-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRXmSKkp6oSJ9zvU9R6Qx7lRQNsggebnk',
    appId: '1:471990946641:ios:7581268e6b4bb1bd672170',
    messagingSenderId: '471990946641',
    projectId: 'web-wrapper-app',
    storageBucket: 'web-wrapper-app.firebasestorage.app',
    iosBundleId: 'com.example.websiteWrapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRXmSKkp6oSJ9zvU9R6Qx7lRQNsggebnk',
    appId: '1:471990946641:ios:7581268e6b4bb1bd672170',
    messagingSenderId: '471990946641',
    projectId: 'web-wrapper-app',
    storageBucket: 'web-wrapper-app.firebasestorage.app',
    iosBundleId: 'com.example.websiteWrapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcDgRYv3QKpA1k05s2J-Em4u9OD5d7__Y',
    appId: '1:471990946641:web:d0342a3b7ed85964672170',
    messagingSenderId: '471990946641',
    projectId: 'web-wrapper-app',
    authDomain: 'web-wrapper-app.firebaseapp.com',
    storageBucket: 'web-wrapper-app.firebasestorage.app',
    measurementId: 'G-Z138XZGBXB',
  );
}
